### ISSUE TITLE
how to use libraries

### ISSUE THREAD

**Issue by govzeja** [alejho/S2S#1]
Hi, sorry if this is the wrong place where ask this and you can delete this post if it's OT but I have a question about libraries in Staubli Robotics Studio and I don't know how to contact you in other way.  I'm using SRS and I want to learn something about how libraries work and how to import one in my application. Can you also explain me how to import your library in my Val3 programs? Because I can't make it works in my application.
Thanks in advantage.

**Comment by alejho** [comment]
write me at **asvilla83 at gmail.com** 
I'll send you some instructions on how to include a library in a VAL3 application!
Ciao!
